# ================= EUREKA =================
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/}
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
